version: '3.9'

services:

  redis:
    image: redis
    container_name: redis1
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    restart: always

  backend:
    build: .
    container_name: backend_django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A core worker --loglevel=info
    depends_on:
      - redis
      - backend

  # smtp4dev service for hande confrim which email   
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://backend:8000/

  workers:
    image: locustio/locust
    volumes:
      - ./core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --workers --master-host master 

volumes:
  smtp4dev-data:

