version: '3.9'

services:

  redis:
    image: redis
    container_name: redis1
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    restart: always

  backend:
    build: .
    container_name: backend_django
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    expose:
      - "8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./core:/app
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A core worker --loglevel=info
    depends_on:
      - redis
      - backend

  nginx:
    image: nginx
    container_name: nginx1
    restart: always
    ports:
      - "80"
    depends_on:
      - backend
      - redis
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/static
      - ./default.conf:/etc/nginx/conf.d/default.conf

volumes:
  static_volume:
  media_volume: