# Generated by Django 4.2.6 on 2024-01-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
