# Generated by Django 4.2.6 on 2024-01-15 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subscription'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
