# Generated by Django 4.2.6 on 2024-01-03 22:36

import blog.validators.blog
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[blog.validators.blog.validate_tag_title])),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[blog.validators.blog.validate_blog_title])),
                ('body', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(max_length=30, validators=[blog.validators.blog.validate_blog_slug])),
                ('image', models.ImageField(upload_to='images/blog/image', validators=[blog.validators.blog.validate_file_image])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='blog.category')),
                ('tag', models.ManyToManyField(related_name='blog', to='blog.tag')),
            ],
        ),
    ]
