# Generated by Django 4.2.6 on 2024-01-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='need_membership',
            field=models.BooleanField(default=False),
        ),
    ]
