# Generated by Django 4.2.6 on 2024-01-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_created_time_blog_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_publick',
            field=models.BooleanField(default=False),
        ),
    ]
