# Generated by Django 4.2.6 on 2024-01-04 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_is_publick'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='is_publick',
            new_name='is_public',
        ),
    ]
